version: "0.1"
environments:
  - name: develop
    branch: develop
    mode: pull-request
apps:
  - name: ui copies
    path: frontend/
    text-resources:
      - path: src/i18n/*.json
        format: nested-key-value
