version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: tailwind-playground
    path: ""
    text-resources:
      - path: "src/components/HelloWorld.vue"
        format: vue-hardcoded
